### ISSUE TITLE
TypeError: 'cmp' is an invalid keyword argument for sort()

### ISSUE THREAD

**Issue by thugcee** [akaihola/pgtricks#14]
Hi, I tried to sort my pg dump and I got:
```
Traceback (most recent call last):
  File "/home/user/.local/bin/pg_dump_splitsort", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.8/site-packages/pgtricks/pg_dump_splitsort.py", line 106, in main
    split_sql_file(sys.argv[1])
  File "/home/user/.local/lib/python3.8/site-packages/pgtricks/pg_dump_splitsort.py", line 96, in split_sql_file
    copy_lines.sort(cmp=linecomp)
TypeError: 'cmp' is an invalid keyword argument for sort()
```

Installed by pip3 on Ubuntu 20.04 with Python 3.8.5.

**Comment by akaihola** [comment]
Hi @thugcee,

Thanks for the bug report! It seems we're not properly Python 3.x compatible here. Definitely needs a fix!

**Comment by akaihola** [comment]
@thugcee, [the 1.0.0 release](https://pypi.org/project/pgtricks/1.0.0/) should fix your problem.
